import {
  BadgeCheck,
  Landmark,
  GraduationCap,
  ScrollText,
  ArrowRight,
  Baby,
  Construction,
  Puzzle,
  Monitor,
  Code,
  Terminal,
  RefreshCw,
  TrendingUp,
  PartyPopper,
  Rocket,
  Settings,
  Users,
  Lightbulb,
  MessageSquare,
  Brain,
  Award,
  Home,
  Package,
  Clock,
  ShieldCheck,
  Building2,
  HeartHandshake,
  Globe,
  Cog,
  Languages,
  Star,
  MapPin,
  Mail,
  Smartphone,
  Phone,
  ExternalLink,
  MessageCircle,
  Send,
  CheckCircle,
  type LucideIcon,
} from "lucide-react";

export const icons: Record<string, LucideIcon> = {
  verified: BadgeCheck,
  account_balance: Landmark,
  school: GraduationCap,
  history_edu: ScrollText,
  arrow_forward: ArrowRight,
  child_care: Baby,
  construction: Construction,
  extension: Puzzle,
  computer: Monitor,
  code: Code,
  terminal: Terminal,
  sync: RefreshCw,
  trending_up: TrendingUp,
  celebration: PartyPopper,
  rocket_launch: Rocket,
  rocket: Rocket,
  settings: Settings,
  groups: Users,
  lightbulb: Lightbulb,
  forum: MessageSquare,
  psychology: Brain,
  leaderboard: Award,
  home_work: Home,
  inventory: Package,
  schedule: Clock,
  verified_user: ShieldCheck,
  business: Building2,
  volunteer_activism: HeartHandshake,
  public: Globe,
  precision_manufacturing: Cog,
  language: Languages,
  star: Star,
  location_on: MapPin,
  mail: Mail,
  phone_iphone: Smartphone,
  call: Phone,
  open_in_new: ExternalLink,
  workspace_premium: Award,
  chat: MessageCircle,
  send: Send,
  check_circle: CheckCircle,
};

export function Icon({ name, ...props }: { name: string; size?: number; className?: string }) {
  const Component = icons[name] ?? CheckCircle;
  return <Component {...props} />;
}
